### ISSUE TITLE
I/O error

### ISSUE THREAD

**Issue by cdupont** [Waziup/WaziGate#47]
From Prince: gateway did not connect to my office wifi, neither did it revert to access point for me to try again so i connected the gateway to a monitor to find that the gateway cant boot up due to some errors from rc.local.
Screenshot: ![IMG_20191120_120843](https://user-images.githubusercontent.com/484033/69245126-8742cc80-0ba6-11ea-840e-96bd20aa97f2.jpg)
Video: https://drive.google.com/drive/folders/1efnHr8m7Msm2YeHtdJrTYIMB76ZZcE3I

**Comment by NerdBishop** [comment]
also i noticed this output was if a form of a loop and it just keeps returning the above lines over and over

**Comment by cdupont** [comment]
@mojtaba-esk @j-forster

**Comment by cdupont** [comment]
Bug confirmed with another team (Senegal). They cannot connect to the gateway with AP.

**Comment by mojtaba-esk** [comment]
When the gateway runs the rc.local it means it is already booted up and those error messages are not important, it just cannot find the OLED display and since it uses another process, it does not block anything.
So, the source of problem must be another thing. I need more information to find the issue. Like asking them to attach a keyboard and try to see the status of the network interfaces and so on.

**Comment by mojtaba-esk** [comment]
Fixed, if there is no OLED does not show errors
