### ISSUE TITLE
Owner of Cloud devices/gateways is not changed when setting the username/password on the UI

### ISSUE THREAD

**Issue by cdupont** [Waziup/WaziGate#7]
When setting the Cloud username and password on the gateway UI, the owner of devices and gateways on the Cloud is not changed if they are already existing.

**Comment by j-forster** [comment]
In the current version the default sync settings are the guest credentials.
See https://github.com/Waziup/waziup-gateway/blob/master/setup/clouds.json
This makes every device owned by _Guest_ and there is no easy way for the user to stop this procedure.

The default credentials allow the synchronization of devices and data points out of the box with no additional settings required, but users should keep in mind that this makes all devices and data points public and free to modify (and delete) for everyone! 

Besides that, a public Guest account might be a security issue for the Waziup Cloud and should be changed in future, maybe make it a read-only account.

The nearest solution is to not provide the Guest account as default account on each Gateway and require the user to provide his valid credentials in order to enable sync.

**Comment by cdupont** [comment]
First part is done on the Cloud:
https://github.com/Waziup/waziup-api/commit/f64cd285f305eed2fef01aafd0dd1f8516454ccc

This adds:
- PUT /devices/XXX/owner
- PUT /gateways/YYY/owner

On the gateway side, you need to call those endpoints to change the ownership of the devices when necessary; i.e. when you detect that the login on the gateway UI as been changed.
Be careful to call the endpoints with tokens from the original owner, to be sure that the ownership transfer can be made. For example:
1. Gateway is configured with user A 
-> devices will be created with owner A
2. The gateway user changes the Cloud setting to user B
-> need to call the endpoint with a token from user A to "give" the devices:

```
TOKEN=`curl -X POST "https://api.waziup.io/api/v2/auth/token" -H  "accept: text/plain;charset=utf-8" -H  "Content-Type: application/json;charset=utf-8" -d "{  \"username\": \"userA\",  \"password\": \"password\"}"`

curl -X PUT "https://api.waziup.io/api/v2/gateways/GW1/owner" -H  "accept: application/json;charset=utf-8" -H  "Authorization: Bearer TOKEN" -H  "Content-Type: text/plain;charset=utf-8" -d "userB"
```

**Comment by j-forster** [comment]
> Be careful to call the endpoints with tokens from the original owner, to be sure that the ownership transfer can be made.

If the device gets restarted (or the network connection breaks) after the user changes the credentials then there is no old token or old credentials to use for the change of the ownership.
Besides that, this auto-ownership-change procedure might not be wanted by the user (because of explicit read-only or write-only (for sensor values) accounts).

> Besides that, a public Guest account might be a security issue for the Waziup Cloud and should be changed in future, maybe make it a read-only account.
>
> The nearest solution is to not provide the Guest account as default account on each Gateway and require the user to provide his valid credentials in order to enable sync.

I think we should go for that solution. It's nice to have the sync feature out of the box without any configuration needed, but besides the obvious security issue it is causing more disadvantages than advantages.

**Comment by cdupont** [comment]
Even if we remove the guest account, the problem remains: what if a user changes the gateway Cloud account from one user to another? The devices will still belong to the old user.
The thing is that in Waziup, the devices ID are unique (using the MAC address or otherwise). Their ID does not depend on the username. 
So it seems to me that we need a procedure to "acquire" an existing device, i.e. change its owner. Is that correct?

**Comment by j-forster** [comment]
If the user changes the credentials at the gateway we should display a note saying:

> Don't forget to change the owner also in the cloud so that the synchronization continues to work with the new account!
>
> [https://dashboard.waziup.io/gateways/myGateway1#change_owner]()
>
> You can also make the device public to allow synchronization from multiple accounts.
> See the FAQ [_How to make a Gateway public?_]()

At the cloud there should be a "Change Owner" button, like there is for devices.

However, this is only needed if the user explicitly changes the credentials.  We should not provide a public guest account but require the user to enter his Waziup account credentials to enable sync. Most user will never changes their credentials after that...

**Comment by cdupont** [comment]
An absolutely required feature is that things should word without configuring anything, out of the box. I see many people have trouble only connecting to the gateway UI.

**Comment by cdupont** [comment]
I think guest accounts could be removed in the future, when we can easily configure the gateway from remote. We could also look into OAouth for the gateway.

**Comment by cdupont** [comment]
Let's close it as gateway does not have guest credentials anymore.
