### ISSUE TITLE
Edge buffer uploading every 5 min too long

### ISSUE THREAD

**Issue by cdupont** [Waziup/WaziGate#72]
Several partners were surprised to see data was arriving at the Cloud only every 5min.
I think we should reduce the default delay value to something lower, such as 10 sec or 30 sec.

**Comment by j-forster** [comment]
With the next release, the "synchronization buffer delay" will become part of the UI and can be set on each sensor separately. However, the default will be to _not synchronize the sensor_ so that the users has to enable the sync for each sensor. This way, the user can decide which sensor will be synchronized and what delay/buffer should be used.
Besides that, it is up to the cloud to deny/forbid very low delays to reduce the overall workload for the cloud, or to limit the number of syncs per day (per user) etc.

**Comment by PaulImison** [comment]
Please also check:
The updates are repeated. e.g. if sending update 1 per min, then the first update is data point. 1-5, the next update is not 6-10, but 1-10, next update is not 11-15, but 1-15 etc. Check the pointer reset. (Also continues even when no data received)

**Comment by cdupont** [comment]
Thanks Paul and Johann.

**Comment by j-forster** [comment]
Changed https://github.com/Waziup/wazigate-edge/commit/1de32669c9754eb1664b8b6c78dd03e32ce52b0e

**Comment by cdupont** [comment]
@j-forster Could this default be configurable through a environment variable? So we can change it at docker-compose level without recompiling the container.

**Comment by cdupont** [comment]
Tested, fixed
