### ISSUE TITLE
V2: remote access not working

### ISSUE THREAD

**Issue by cdupont** [Waziup/WaziGate#91]
Not sure about the status of remote access in this version.
On the Cloud dashboard, if I click on "remote access", I currently get "gateway timeout".
The URL is probably bad too (it doesn't have admin now): `https://remote.waziup.io/b827ebe6be77/admin/`

**Comment by j-forster** [comment]
The basic tunnel issue is fixed by these commits:
https://github.com/Waziup/wazigate-dashboard/commit/ccad2f6521354f920044f70dd9ee804c56a5b278
https://github.com/Waziup/waziup-js/commit/3b7aa99a767b00df527e76a9bea148d1b0056673

However, some functions are still not working with the tunnel:

- [x] Logout does nothing
- [x] Apps show "HTTP Error 401 Unauthorized"

I will hand this over to @mojtaba-esk.

**Comment by mojtaba-esk** [comment]
I still see the timeout error.
One more thing, when I change the ID of the gateway in the Wazigate dahsboard and turn off and on the sync to get it reflected on the cloud dashboard, I cannot access it via the remote. I get this error:

`Not allowed to access this gateway.`

**Comment by cdupont** [comment]
Working now, however the dashboard address is e.g.  https://remote.waziup.io/0242ac120003ccde/admin/
With a superfluous /admin.
@j-forster could you add a 304 route on the gateway?

**Comment by cdupont** [comment]
Current redirect gives strange results:
![Peek 2020-11-23 12-44](https://user-images.githubusercontent.com/484033/99958547-dd35eb80-2d89-11eb-9eb1-8c893badaa85.gif)

**Comment by cdupont** [comment]
Working now, closing
