### ISSUE TITLE
V2: Sync page

### ISSUE THREAD

**Issue by cdupont** [Waziup/WaziGate#97]
I create this issue to centralize some comments on the "Sync" page.

![image](https://user-images.githubusercontent.com/484033/97702917-0e373f00-1ab0-11eb-8230-32dc85c6c24c.png)

1. "Rename" might not be useful
As the Cloud name is not used and is just informative, rename button could be removed.

2. Why not putting a "Apply" "Reset" buttons at the bottom?
Now the "Active Sync" button need to be switched off, changes are made, and then switched on again.
It works fine, but maybe it's clearer with a traditional form.

**Comment by j-forster** [comment]
"Rename" is a very primitive function that does exatly what it says. The fact that it is informative does not mean that it is useless.
The gateway is able to sync with multiples clouds, but the UI is pinned to the Waziup Cloud. However, new clouds can be created by calling the API manually, and will be displayed by the UI, too.

There is no "Apply" and "Reset" because changing settings requires the active sync process to be stopped. We put a big "Active Sync" switch on top of that dialog box and disabled all the inputs, so that the user knows that he has to stop the active synchronization in order to make changes.

**Comment by cdupont** [comment]
I understand that synchronization need to be switched off in order to be able to change settings.
However, why not decoupling the notions of "I want to activate/deactivate sync" and "I want to edit settings"?
For instance, a user might want to stop syncing while not wanting to change any settings. So for me, those are two different things. We could have edit/apply buttons that become active after the sync is switched off. It would be more clear for the user that his settings have been taken into account (and checked for validity when he clicks "apply"). Otherwise, it's not clear for the user that his settings will be checked/applied when flipping back on.
